config/routes.rb
Rails.application.routes.draw do
  devise_for :managers

  root 'homes#index'

  resources :drivers
  resources :trips
  # resources :drivers do
  #   resources :trips
  # end
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :trips, dependent: :destroy
  has_many :managers, through: :trips

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips, dependent: :destroy
  has_many :drivers, through: :trips


end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :manager
  belongs_to :driver

  validates :title, presence: true, uniqueness: true
  validates :note, presence: true
  # validates :startingpoint, presence: true
  validates :endingpoint, presence: true
  # validates :startingtime, presence: true
  # validates :endingtime, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :authenticate_manager!

  def new
    @driver = Driver.new
  end

  def create
    @driver         = Driver.new(driver_params)
    if @driver.save
      redirect_to drivers_path, notice: "Driver created!"
    else
      flash[:alert] = "See errors below"
      render :new
    end
  end

  def index
    @drivers = Driver.all
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])
    if @driver.update(driver_params)
      redirect_to driver_path(@driver), notice: "Driver updated!"
    else
      flash[:alert] = "See errors below"
      render :edit
    end
  end

  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy
    redirect_to drivers_path, notice: "Driver deleted!"
  end

  private

  def driver_params
    params.require(:driver).permit(:name, :location)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_manager!

  def new
    @trip = Trip.new
  end

  def create
    @trip         = Trip.new(trip_params)
    @trip.manager = current_manager
    if @trip.save
      redirect_to trip_path(@trip), notice: "Trip created!"
    else
      flash[:alert] = "See errors below"
      render :new
    end
  end

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to trip_path(@trip), notice: "Trip updated!"
    else
      flash[:alert] = "See errors below"
      render :edit
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path, notice: "Trip deleted!"
  end

  def trip_params
    params.require(:trip).permit(:title,
                                 :note,
                                 :startingpoint,
                                 :endingpoint,
                                 :startingtime,
                                 :endingtime,
                                 :driver_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/drivers/_form.html.erb
<%= form_for @driver, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary", data: {disable_with: "saving.."} %>
<% end %>

app/views/drivers/index.html.erb
<div class="container">
  <h1>All Drivers</h1>
  <% @drivers.each do |d| %>
    <h3><%= link_to d.name, driver_path(d) %></h3>
  <% end %>
</div>

app/views/drivers/new.html.erb
<div class="container center_div">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">

      <h1>New</h1>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/drivers/show.html.erb
<h2>Driver's information</h2>

<h3><%= @driver.name %></h3>
<h3><%= @driver.location %></h3>

<%= link_to "Edit", edit_driver_path(@driver), class: "btn btn-info" %>
<%= link_to "Delete", driver_path(@driver), method: :delete,
            data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Lean Fleet</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to "Trips", new_trip_path %>
                </li>
                <li>
                    <%= link_to "Drivers", drivers_path %>
                </li>
                <li>
                    <%= link_to "Manager", manager_session_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VSW</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "/layouts/nav" %>

<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<%= form_for @trip, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :driver %>
    <%= f.collection_select :driver_id, Driver.order(:id),:id, :name %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :endingpoint %>
    <%= f.text_field :endingpoint, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :note %>
    <%= f.text_area :note, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary", data: {disable_with: "saving.."} %>
<% end %>

app/views/trips/edit.html.erb
<div class="container center_div">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">

      <h1>Edit</h1>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container">
  <h1>List of trips.</h1>

  <div class="chartdiv">
    <%= image_tag "chart.jpg" %>
  </div>
</div>

<!-- <% @trips.each do |t| %>
  <h2><%= link_to t.title, trip_path(t) %></h2>
<% end %> -->

app/views/trips/new.html.erb
<!-- <p>Dispatch view</p> -->
<!-- To:Koan Let's talk about Dispatch later. For now, I just put thie code here.(Kosuke) -->

<!-- (Memo) How to send json data from Rails to Node as Dispatch. -->

<div class="container center_div">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">

      <h1>New</h1>

      <%= render "form" %>

    </div>
  </div>
</div>

app/views/trips/show.html.erb
<h2>Driver's information</h2>

<h3>Title : <%= @trip.title %></h3>
<h3>Note : <%= @trip.note %></h3>
<h3>Ending Point : <%= @trip.endingpoint %></h3>
<h3>Driver : <%= @trip.driver.name %></h3>

<%= link_to "Edit", edit_trip_path(@trip), class: "btn btn-info" %>
<%= link_to "Delete", trip_path(@trip), method: :delete,
            data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>

<br>
<br>
<button onClick="sendJob()" class="btn btn-success">Notify for driver</button>

<script src="http://leanfleet.com:3001/socket.io/socket.io.js">
</script>

<script>
  socket = io.connect('http://leanfleet.com:3001');
  function sendJob(){
    socket.emit('sendJob', {endingpoint: "<%= @trip.endingpoint %>", driver_id: 1 })
  }
</script>